/*
    Generated by Atomist on 09 07 2016 
*/
package com.jackie;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = MyawesomeserviceApplication.class)
@WebAppConfiguration
public class MyawesomeserviceApplicationTests {

	@Test
	public void contextLoads() {
	}
}
