/*
    Generated by Atomist on 09 07 2016 
*/
package com.jackie;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class MyawesomeserviceApplication {

    public static void main(String[] args) {
        SpringApplication.run(MyawesomeserviceApplication.class, args);
    }
}
