/*
    Generated by Atomist on 09 07 2016 
*/
package com.jackie;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
* Spring Java configuration file for Myawesomeservice.
* Don't even think of using XML.
*/
@Configuration
public class MyawesomeserviceConfiguration {

    // Your beans go here ... 
	// Atomist Bot suggests "maybe use an Atomist project editor to add a sample one?"
}
