/*
    Generated by Atomist on 09 07 2016 
*/
package com.jackie;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class PingController {

    @RequestMapping(path = "/ping")
    public String ping() {
       return "pong";
    }
}